### PR TITLE
feat: change JVM chart tooltip background

### LINKED ISSUE #103: JVM chart tooltip not formatted like other charts
Need to change backround/text color for the JVM chart tooltip: (currently white and hard to read)

Screenshot 2024-07-22 at 9 32 27 AM

should look like this:

Screenshot 2024-07-22 at 9 32 47 AM

### PR DESCRIPTION
**Pull request by shlomomdahan**
closes #103 

Screenshot 2024-07-22 at 9 38 26 AM

### CODE REVIEW

**Comment by Vandit1604** [comment]
Thanks for the PR @shlomomdahan,
The tooltip overlaps the legend on the side on smaller screens. I think the placement of the legend should be on the left where the chart line originates, but I'm open for other suggestions.
I don't know what the number on the legend represent right now (version? I guess). Likewise, I think for a new user, we should label them for better understanding

**Comment by shlomomdahan** [comment]
@Vandit1604 Thank you for the feedback.

It seems like Echarts doesn't support adding additional text or titles to the legend. I guess the chart title would need to be more descriptive in that case? I was just using the existing chart (https://community.jenkins.io/t/jvms-by-date-graph/15738) for reference and it doesn't seem to be more descriptive.

Additionally, I tried moving the legend to the left, but it does look a bit weird. Do you mind screenshotting the issue you saw so I can get a better idea? I think responsiveness is never going to be perfect here. Even on the echarts examples on their website there is overlap with the toolbox etc on smaller screens.

**Comment by Vandit1604** [comment]
> It seems like Echarts doesn't support adding additional text or titles to the legend. I guess the chart title would need to be more descriptive in that case?

We can definitely do that for better understanding.

> I think responsiveness is never going to be perfect here. Even on the echarts examples on their website there is overlap with the toolbox etc on smaller screens.

I agree, we can't be responsive for all the screen sizes with this much information to be shown.

**Comment by Vandit1604** [comment]
I think we can at least add more descriptive title for the chart for better understanding.

**Comment by krisstern** [comment]
I think additional details may not be necessary. @gounthar What do you think?

**Review by krisstern — APPROVED** [review]
LGTM

**Comment by gounthar** [comment]
The deployment looks good to me.
Having percentages in the tooltip would have been useful for me. 🤷

**Pull request merged**
