### PR TITLE
feat: add optional tag only when optional = true

### PR DESCRIPTION
**Pull request by shlomomdahan**
Per @krisstern meeting with Mark - adds an optional flag only when optional = true. Otherwise just lists the rep. 

Screenshot 2024-08-05 at 1 20 16 PM

### CODE REVIEW

**Comment by Vandit1604** [comment]
Hey @shlomomdahan, I wasn't present in the last meeting. Can you give some more context what are we actually doing in this PR.
Thanks

**Comment by shlomomdahan** [comment]
@Vandit1604 

Sure - this PR just removed the Optional tag for dependencies that are NOT optional. Looks less cluttered / cleaner

**Review by Vandit1604 — APPROVED** [review]
Thanks @shlomomdahan 
Looks good to me!

**Review by krisstern — APPROVED** [review]
LGTM

**Pull request merged**
