### PR TITLE
feat: compare statistics trends (stats-in-detail page)

### PR DESCRIPTION
**Pull request by shlomomdahan**
@krisstern @gounthar @Vandit1604 

How do you guys feel about implementing the compare feature this way? 

The user can select up to 2 charts at a time to compare. 

ref: 
- #80 

Screenshot 2024-07-16 at 12 19 32 PM
Screenshot 2024-07-16 at 12 19 44 PM
Screenshot 2024-07-16 at 12 19 57 PM

### CODE REVIEW

**Comment by gounthar** [comment]
That's interesting. 🤔 
I guess adding three would be non-feasible due to three different scales.
Thanks.

**Comment by krisstern** [comment]
I am more inclined to have two plots scaled to 100% in height using two different scales, with one scale shown on the left and the other shown on the right, as controled by two dropdown menus in its own container in the bottom to show which side is showing which scale. In that case we will be able to make sure at most only two plots are chosen at any one time.

**Comment by shlomomdahan** [comment]
@krisstern @gounthar @Vandit1604 

If I understand correctly, is the below what you are looking for? This way we have mutually exclusive selectors and side by side charts. Please let me know your thoughts

Screenshot 2024-07-17 at 12 46 48 PM

Screenshot 2024-07-17 at 12 47 12 PM

Screenshot 2024-07-17 at 12 47 54 PM

**Comment by krisstern** [comment]
@shlomomdahan Maybe try overlaying the two plots together? I think that's what we (@gounthar and I) meant earlier.

**Comment by gounthar** [comment]
> @shlomomdahan Maybe try overlaying the two plots together? I think that's what we (@gounthar and I) meant earlier.

Yes indeed. 👍

**Comment by shlomomdahan** [comment]
@krisstern @gounthar 

Can you please explain what you mean by overlaying the two graphs together?

I think the first example was closer to what you are suggesting now.

**Comment by krisstern** [comment]
I think we prefer something like https://echarts.apache.org/examples/en/editor.html?c=mix-line-bar or https://echarts.apache.org/examples/en/editor.html?c=multiple-y-axis where you can have two or more y-axes.

**Comment by shlomomdahan** [comment]
@krisstern @gounthar 

Got it! I'll work on it today.

**Comment by shlomomdahan** [comment]
@krisstern @gounthar 

I think the below highlights the issue with the approach of having two drastically different scales plotted together.

As you can see below, the line with the smaller value still 'appears' to be larger than the other. I think jthisa can potentially be misleading to users. 

What are your thoughts? 
Thank you

Screenshot 2024-07-18 at 9 17 02 AM

**Comment by krisstern** [comment]
I think that is why it is a good idea to use a color-coded scheme to clearly differentiate the two plots and the two y-axes, which has not been applied in the example shown yet.

**Comment by shlomomdahan** [comment]
@krisstern 

Can you please specify further what you mean by color-coded scheme? Even with the Y-axes color coded, the way the data represented will still be misleading.

I think the first approach works best, with the Y axis scaled to the largest values shown.

**Comment by lemeurherve** [comment]
As the Y axis represent the same type of value in both plots I agree that
the first approach seems the most appropriate for these particular
comparisons.

**Comment by shlomomdahan** [comment]
Marking ready for review per @lemeurherve comments.

On a side note - I see drastically better loading / performance of the site after the recent update of #91.
Do you guys also notice an improvement?

**Comment by gounthar** [comment]
Yes, it's faster than last week.

**Review by gounthar — DISMISSED** [review]

**Review by krisstern — CHANGES_REQUESTED** [review]
@shlomomdahan Please revise control design as they are not very obvious or intuitive as of now. Also if we do not normalise the scales for comparing patterns (and not values) there is a chance I would not be able to compare the trends at all, like shown in this screenshot:

Screenshot 2024-07-19 at 12 30 57 AM

**Comment by shlomomdahan** [comment]
@krisstern 

Sure - I'll update the controls.

As for the issue with the comparison in the image above you've shared - this is because the maximum value for jenkins installations is around ~300,000 while for plugins it's about 35,000,000. 

Given the other attempt to display this data effectively, do you have any other potential solutions in mind?

**Comment by krisstern** [comment]
Maybe just normalised both plots to 100% in height and use color coded y-axis and plot lines like they do at https://echarts.apache.org/examples/en/editor.html?c=multiple-y-axis so you would have the ability to at least see the trends? This would not be misleading if you clearly differentiate the two scales and therefore two plots, like they do here: https://matplotlib.org/stable/gallery/subplots_axes_and_figures/two_scales.html. Comparing two scales this way is more commmon place than you tend to believe especially in the sciences.

**Comment by shlomomdahan** [comment]
@krisstern,

I understand your point, but I’ve tried that in previous examples and found it misleading. The issue with this approach in our context is that, while we are comparing the number of installations, jobs, etc., they all represent quantities. In the provided examples, the two axes display values that are closely related and make sense when shown together. For example temp and precipitation..

**Comment by shlomomdahan** [comment]
@krisstern,

I understand your point, but I’ve tried that in previous examples and found it misleading. The issue with this approach in our context is that, while we are comparing the number of installations, jobs, etc., they all represent quantities. In the provided examples, the two axes display values that are closely related and make sense when shown together. For example temp and precipitation..

Here is again what you are describing with color coded lines and axes.

Screenshot 2024-07-18 at 2 06 14 PM

**Comment by krisstern** [comment]
Yeah, I definitely find the latest version a lot more agreeable. Since even though all the scales are showing quantities, they naturally fall on scales that are vastly different and may make direct comparison of their trends impossible in some cases. The latest implementation seems to fix this issue.

**Comment by gounthar** [comment]
I love the last proposal.

**Review by gounthar — DISMISSED** [review]

**Comment by krisstern** [comment]
It looks like we have broken something in the SVG download in the process:

Screenshot 2024-07-19 at 6 53 29 PM

**Comment by shlomomdahan** [comment]
@krisstern 

Above issue has been fixed. There was a formatting issue with the chart theme file causing the problem.

**Review by krisstern — APPROVED** [review]
LGTM

**Comment by krisstern** [comment]
@Vandit1604 Could you please give this PR a review?

**Review by Vandit1604 — APPROVED** [review]
@shlomomdahan thanks for the good work!

**Pull request merged**
