### PR TITLE
feat: update React version to v19

### LINKED ISSUE #275: Upgrade to React v19
### What feature do you want to see added?

Would like to have the repo's React dependency to be upgraded from v18 to v19.

### Upstream changes

N/A

### PR DESCRIPTION
**Pull request by saurabhraghuvanshii**
Closes #275
PR updates React version from v18 to v19.

### CODE REVIEW

**Comment by krisstern** [comment]
Could you please check to see if the build has succeeded locally before pushing to GitHub?

**Comment by krisstern** [comment]
It appears a lot more work is needed to be done for the issue concerned as per https://react.dev/blog/2024/04/25/react-19-upgrade-guide

**Comment by saurabhraghuvanshii** [comment]
@krisstern  i see on website there is no problem showing.

**Comment by saurabhraghuvanshii** [comment]
@krisstern ok I see.

**Comment by krisstern** [comment]
Could you please run build like I have said using:
```console
npm run build
```
instead of just testing in the dev mode?

**Comment by saurabhraghuvanshii** [comment]
@krisstern ok, I see now it show error .

**Comment by saurabhraghuvanshii** [comment]
@krisstern by running i only face in Navbar.tsx and in footer.tsx   the error showing is 
               Property 'jio-footer' does not exist on type 'JSX.IntrinsicElements'  I tried several things but show same error

**Comment by saurabhraghuvanshii** [comment]
@krisstern can I use //@ts-ignore

**Comment by krisstern** [comment]
> @krisstern can I use //@ts-ignore

Normally you are not allowed to use the `// @ts-ignore` comment to disable a type-checking.

**Comment by krisstern** [comment]
@saurabhraghuvanshii If you are not sure what to do, I could take over. This task is not supposed to be easy.

**Comment by saurabhraghuvanshii** [comment]
@krisstern I will give a try

**Comment by saurabhraghuvanshii** [comment]
Only problem come in jio-footer and jio-navbar there types problem in v19 , i tried every possible things but it doesn't work

**Comment by saurabhraghuvanshii** [comment]
@krisstern sir I think it problem with v19 , I test every thing and every types but typescript show same error but. when we keep @types/react v18 to it does not show error.

**Comment by krisstern** [comment]
Thanks @saurabhraghuvanshii I will take it from here.

Also, you stated that you have tried "everything" but could you please state here what you have actually tried?

**Comment by saurabhraghuvanshii** [comment]
@krisstern I tried to change components-elements.d.ts , tsconfig.json in which I change bundler to node , and learn from resources about the error I am facing and change according to it but , it doesn't work ,type support with v18 with react v19 but both v19 same doesn't work , sorry sir for distributing.

**Comment by saurabhraghuvanshii** [comment]
Every time it show same error nothing new change .

**Comment by krisstern** [comment]
Thanks! I was able to fix the issues in #254.

**Comment by saurabhraghuvanshii** [comment]
@krisstern changes you done I have done but doesn't work for me.

**Comment by krisstern** [comment]
I checked I made more changes then you have, please check carefully again.

**Comment by saurabhraghuvanshii** [comment]
I changed locally doesn't commit that changes, but your changes are good btw you're senior. I look that changes to learn more

**Pull request closed without merging**
