### PR TITLE
feat(data): Adds a list of plugins and their dependencies.

### PR DESCRIPTION
**Pull request by gounthar**
## Overview

As discussed in our [weekly meeting](https://docs.google.com/document/d/1vFY1NSG1TczqYscrDQzixUSJ5eYq1v78k5l3J5ZNZIM/edit#heading=h.u70kwg9xloew), this PR proposes to add the current list of plugins provided by the update center, along with their dependencies.

## Data Source

The data is sourced from the [JSON file](https://updates.jenkins.io/current/update-center.actual.json) supplied by the update center.

## Data Processing

The JSON file has been cleaned up to retain only the list of plugins and their dependencies on other plugins.

## Purpose

The primary aim of this addition is to serve as a source of truth for generating a [plugins dependency graph](https://stats.jenkins.io/jenkins-stats/jenkinsgraph.html?filter=kohsuke) with a more modern and user-friendly appearance.

## Future Plans

A subsequent PR will be submitted to implement a system for regular updates of this file using updatecli.

## Next Steps

1. Review the added data for accuracy and completeness
2. Discuss any potential modifications or enhancements to the data structure
3. Consider the implications and benefits for the plugin dependency graph project

Your feedback and suggestions on this addition are greatly appreciated.

### CODE REVIEW

**Comment by shlomomdahan** [comment]
Thank you @gounthar!

Do you think it would be useful to keep the additional data that the file brings in?

So we could include it as below?

Screenshot 2024-07-22 at 1 50 27 PM

**Comment by gounthar** [comment]
I appreciate your suggestion and understand the intent to create a comprehensive data structure. However, my initial aim was to keep the data structure as simple as possible. 😉

## Current Stance
- Not opposed to the idea of a more detailed structure
- Preference for simplicity in the initial implementation

## Next Steps
1. Let's gather opinions from other team members on what approach we should take.
2. We should consider the trade-offs between simplicity and comprehensiveness.

## Question for Consideration
Is this data already available elsewhere in our system? If so, we might want to avoid duplication and instead focus on how to best utilize or integrate with existing resources.

## Moving Forward
- Let's open this up for discussion with the wider team.
- We can weigh the pros and cons of different data structures.
- Our decision should balance simplicity, usability, and long-term maintainability.

**Comment by lemeurherve** [comment]
I would keep the data gathering in infra-statistics repository instead of
starting doing so in this frontend repository.

**Comment by shlomomdahan** [comment]
New PR #115 should implement @lemeurherve suggestions above.

**Pull request closed without merging**
