### PR TITLE
feat: use dynamic imports to improve site loading speed

### PR DESCRIPTION
**Pull request by shlomomdahan**
This PR should address all of our concerns with the site speed. 

I switched to dynamic imports - following the Vite documentation for static imports:

https://vitejs.dev/guide/assets

ex:
Screenshot 2024-07-23 at 1 11 11 PM

Site now loads almost instantaneously and there isn't much performance delay (perhaps slightly longer to load up all the plugin cards on the trends page - I can address this in a separate PR if needed).

Let me know what you guys think!

### CODE REVIEW

**Comment by krisstern** [comment]
Hi @shlomomdahan, you have some linting issues with this PR which need to be addressed:
```shell
[2024-07-23T17:14:04.853Z] + npm run lint
[2024-07-23T17:14:05.154Z] 
[2024-07-23T17:14:05.155Z] > stats2.jenkins.io@0.0.0 lint
[2024-07-23T17:14:05.155Z] > eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0
[2024-07-23T17:14:05.155Z] 
[2024-07-23T17:14:07.161Z] 
[2024-07-23T17:14:07.161Z] /home/jenkins/agent/workspace/Websites_stats_PR-110/vite.config.ts
[2024-07-23T17:14:07.161Z]   4:10  error  'resolve' is defined but never used  no-unused-vars
[2024-07-23T17:14:07.162Z]   4:10  error  'resolve' is defined but never used  @typescript-eslint/no-unused-vars
[2024-07-23T17:14:07.162Z] 
[2024-07-23T17:14:07.162Z] ✖ 2 problems (2 errors, 0 warnings)
[2024-07-23T17:14:07.163Z] 
```

**Comment by Vandit1604** [comment]
The cards on Plugin Installation Trend page is not loading for me. How much time is expected before the cards will load??

**Comment by shlomomdahan** [comment]
@Vandit1604 3-4 seconds on my end

**Comment by shlomomdahan** [comment]
@Vandit1604 

Can you try again and see if performance improved? I switched to a batch import method which should reduce the load of the fetch calls and improve performance.

**Comment by Vandit1604** [comment]
Now, they are loading pretty fast (~3 seconds) for me.

**Review by Vandit1604 — APPROVED** [review]

**Review by krisstern — APPROVED** [review]
LGTM

**Review by gounthar — APPROVED** [review]

**Pull request merged**
