### PR TITLE
feat: adds dependency graph page

### LINKED ISSUE #111: feat: add dependency graph page / feature to the site
### What feature do you want to see added?

Implement the dependency graph page.

https://stats.jenkins.io/jenkins-stats/jenkinsgraph.html?filter=kohsuke

### Upstream changes

N/A

### PR DESCRIPTION
**Pull request by shlomomdahan**
Introduces new dependency graph feature to the site. 
Built with react-force-graph-3d: https://github.com/vasturiano/react-force-graph?tab=readme-ov-file

I tried building this with eCharts, but unfortunately it was too limiting and did not work well. We could work on incrementally adding functionality to this, but it the meantime it works very similar to the dependency graph on the old site. 

Please let me know your thoughts.

closes #111 

Screenshot 2024-07-28 at 11 36 21 AM
Screenshot 2024-07-28 at 11 38 29 AM

### CODE REVIEW

**Comment by shlomomdahan** [comment]
NOTE: I am using a local file for the data, so you will not be able to see in deployment.

I will show a demo on Monday's call until we sort out the best way to gather the data.

**Comment by krisstern** [comment]
The data is showing now! This is looking really fantastic

**Comment by gounthar** [comment]
Yes, that looks great!

**Comment by lemeurherve** [comment]
image

**Review by krisstern — APPROVED** [review]
LGTM

**Review by Vandit1604 — APPROVED** [review]

**Pull request merged**
