### PR TITLE
fix: fix a chart and stats table height issue from previous (PR #39)

### PR DESCRIPTION
**Pull request by shlomomdahan**
This PR makes sure that the size of the container holding the charts and table takes up the full size of the container, and well as ensuring that the mobile swappable drawer does not overlap the content when user is in mobile view.

### CODE REVIEW

**Comment by shlomomdahan** [comment]
@krisstern @Vandit1604 

Can we merge if this look OK?

Thanks

**Comment by krisstern** [comment]
This PR will need to be reviewed first before we could approve it and merge it. 

@Vandit1604 could you please give this PR a review as soon as possible? Thanks!

**Review by krisstern — CHANGES_REQUESTED** [review]
The refresh button is too close to the heading for example with the "iPhone 12 Pro" in this chart for example:

Screenshot 2024-06-26 at 11 31 48 PM

Please make adjustments accordingly.

**Comment by shlomomdahan** [comment]
@krisstern 

I will open a separate PR for that. 

That needs to be addressed on every single chart and I do not want to commingle the fixes on this PR.

**Comment by krisstern** [comment]
@shlomomdahan If that is the case, please open an issue to track. Thanks!

**Comment by shlomomdahan** [comment]
@krisstern issue #59 created to track char titles

**Comment by shlomomdahan** [comment]
@krisstern @Vandit1604 

Merge conflicts resolved

**Comment by krisstern** [comment]
@shlomomdahan There are some build failures in your PR, please fix before we can approve it

**Comment by krisstern** [comment]
BTW, can we add a feature to make the arrows clickable as well maybe in a new PR?

**Comment by krisstern** [comment]
Some are clickable and some are not currently, which is pretty awkward...

**Review by krisstern — APPROVED** [review]

**Comment by shlomomdahan** [comment]
@krisstern Can you explain what you mean by clickable arrows? If you are referring to the mobile bottom drawer open arrows, then that is actually the intended functionality from MUIs component as it's meant to be for touchscreen devices. But I believe I can add the ability too have I open on clicking as well if that's preferable. However it might interfere with the swiping gesture.

Up to you guys. Open to adding it.

**Pull request merged**
