### PR TITLE
feat: populate plugin-trends page with local data

### PR DESCRIPTION
**Pull request by shlomomdahan**
this is PR 2/3 for populating the site with local data.

Something I noticed on this PR - when loading the site locally with ```npm run dev``` the site take very long to load (15-20 seconds). Locally, it looks like the majority of this is being caused by the glob import of 2,000+ plugin Json files.
However, when the site is actually deployed on netlify, It works fast and there is no apparent delay. Does anyone know why this is the case? 

ref:

- #68

### CODE REVIEW

**Comment by krisstern** [comment]
Have you tried to compare your app's performance in the dev environment and the production-like env? So by the former I mean doing `npm run dev` and the latter I mean doing `npm run build && npm run preview`. If this makes a significant difference, it is likely because in the production-like environment you are serving a optimized and minimized version of the source code / single-page app in the "dist" (for "distributable", while in the dev environment you are serving raw non-minified code in the "src" folder.

**Review by gounthar — COMMENTED** [review]
It's not slow for me. 🤔

**Comment by shlomomdahan** [comment]
> Have you tried to compare your app's performance in the dev environment and the production-like env? So by the former I mean doing `npm run dev` and the latter I mean doing `npm run build && npm run preview`. If this makes a significant difference, it is likely because in the production-like environment you are serving a optimized and minimized version of the source code / single-page app in the "dist" (for "distributable", while in the dev environment you are serving raw non-minified code in the "src" folder.

@krisstern 

I tried `npm run build && npm run preview` and it works perfectly!

" If this makes a significant difference, it is likely because in the production-like environment you are serving a optimized and minimized version of the source code / single-page app in the "dist" (for "distributable", while in the dev environment you are serving raw non-minified code in the "src" folder."

In this case, is there anything we should do about it? Or are we ok to leave as-is?

Thanks

**Comment by shlomomdahan** [comment]
Additionally, I tried to clean up the commit history on this branch by squashing all the commits from the previous branch into a single commit. This branch was an extension of #70 so when I checked out the branch, it brought over all of the file changes and commits from the previous.

Marking as ready to review-

**Comment by krisstern** [comment]
> In this case, is there anything we should do about it? Or are we ok to leave as-is?

I think we can leave things as-is for now.

**Comment by krisstern** [comment]
> Additionally, I tried to clean up the commit history on this branch by squashing all the commits from the previous branch into a single commit. This branch was an extension of #70 so when I checked out the branch, it brought over all of the file changes and commits from the previous.
> 
> Marking as ready to review-

Looks okay for me!

**Review by gounthar — APPROVED** [review]
Same.

**Review by Vandit1604 — APPROVED** [review]
Everything looks fine to me.
Thanks for the hard work @shlomomdahan

**Pull request merged**
