### PR TITLE
docs: add local dev instructions

### PR DESCRIPTION
**Pull request by shlomomdahan**

### CODE REVIEW

**Review by gounthar — APPROVED** [review]
The instructions worked for me, I was able to deploy the site locally.

I guess the warnings during the install phase aren't that much of an issue?

 ```
npm install
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 305 packages, and audited 306 packages in 2m

57 packages are looking for funding
  run `npm fund` for details

2 vulnerabilities (1 moderate, 1 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice
npm notice New patch version of npm available! 10.8.0 -> 10.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
npm notice To update run: npm install -g npm@10.8.1
npm notice
```

**Comment by krisstern** [comment]
Hi @shlomomdahan, we are missing instructions for the preview step in https://vitejs.dev/guide/static-deploy.html#deploying-a-static-site for after having built the site locally. Please add this.

**Comment by lemeurherve** [comment]
Is it really needed?

There is a local webserver running with `npm run dev`, and previews with Netlify on every pull request here, seems enough to me.

**Comment by lemeurherve** [comment]
> I guess the warnings during the install phase aren't that much of an issue?

It is 😅 

Opened #17

**Comment by krisstern** [comment]
> Is it really needed?
> 
> There is a local webserver running with `npm run dev`, and previews with Netlify on every pull request here, seems enough to me.

Yes, it is needed

**Pull request merged**
