### PR TITLE
feat: populate plugins-versions page with local data 

### PR DESCRIPTION
**Pull request by shlomomdahan**
This is PR 3/3 for populating the site with local data.

This PR is an extension of #76. Converting to draft until #76 is approved and merged.

ref:
- #68

### CODE REVIEW

**Comment by gounthar** [comment]
Would it make sense to have a graph showing at the same time the monthly plugin usage, the total jobs, the monthly Jenkins installations, and the total nodes?

**Comment by shlomomdahan** [comment]
> Would it make sense to have a graph showing at the same time the monthly plugin usage, the total jobs, the monthly Jenkins installations, and the total nodes?

I personally think it might clutter the page and be redundant with the other pages. But I'll leave it to @krisstern and @Vandit1604 to let me know what they think. Happy to work on that in a separate PR if needed!

**Comment by Vandit1604** [comment]
Would it be possible to incorporate the overall trends on a single page, with a smaller size? Seeing all them on a single page can be easy to browse the overall statistics i.e. how many Jenkins installations were done, how many jobs were executed, total nodes over time. 

WDYT about that @krisstern @gounthar @shlomomdahan ?

**Comment by gounthar** [comment]
That's why I proposed earlier to combine them.

**Comment by shlomomdahan** [comment]
@gounthar @Vandit1604 @krisstern 

Issue #80 has been opened on the above suggestions

**Review by krisstern — APPROVED** [review]

**Pull request merged**
