### PR TITLE
feat: improve charts

### PR DESCRIPTION
**Pull request by shlomomdahan**
1. Made slight responsiveness improvements
2. Renders charts as SVG to enable downloading of SVG of the chart

### CODE REVIEW

**Comment by Vandit1604** [comment]
Thanks @shlomomdahan for the PR.

**Comment by Vandit1604** [comment]
Thanks @shlomomdahan for the PR.
Overall Looks good to me.

WDYT @krisstern

**Review by krisstern — CHANGES_REQUESTED** [review]
I have tried out downloading as SVG but have encountered some problems with the legend. More specifically if I download one with a long legend, the legend gets truncated, like below:

Screenshot 2024-06-24 at 12 17 57 AM

I think we will need to come up with a clever solution to this.

**Comment by krisstern** [comment]
But I think this may be fixed by #49. So let's have that reviewed and merged first and come back to this one.

**Review by krisstern — APPROVED** [review]
Can confirm that merging #49 fixes the pie chart legend issue.

**Pull request merged**
