### PR TITLE
feat: add swipeable drawer for mobile view (stats page)

### PR DESCRIPTION
**Pull request by shlomomdahan**
use a pull up drawer for mobile

Screenshot 2024-06-19 at 9 15 48 PM

### CODE REVIEW

**Comment by Vandit1604** [comment]
@shlomomdahan This is very cool.

Nice to have feature for smaller devices.

**Comment by Vandit1604** [comment]
We can use https://react-icons.github.io/react-icons/search/#q=MdOutlineKeyboardDoubleArrowUp icon to help first time users in clicking/swiping up the drawer bleeding. This is for better UX.

**Review by krisstern — CHANGES_REQUESTED** [review]
Please make changes as per suggestion made by @Vandit1604:

> We can use https://react-icons.github.io/react-icons/search/#q=MdOutlineKeyboardDoubleArrowUp icon to help first time users in clicking/swiping up the drawer bleeding. This is for better UX.

**Comment by shlomomdahan** [comment]
@Vandit1604 @krisstern 

Changes made 👍 

Screenshot 2024-06-23 at 12 23 30 PM
Screenshot 2024-06-23 at 12 23 41 PM

**Comment by Vandit1604** [comment]
Thanks @shlomomdahan 
PR looks good to me.
WDYT @krisstern

**Review by krisstern — CHANGES_REQUESTED** [review]
I checked that when the "Overall Trends" and "Monthly Analysis" are collapsed their button heights are different from when they are not, and the difference is very noticeable:

Screenshot 2024-06-24 at 12 50 39 AM
Screenshot 2024-06-24 at 12 50 51 AM

Could we please make their height consistent throughout?

**Comment by shlomomdahan** [comment]
Screenshot 2024-06-23 at 1 37 18 PM

@krisstern 
Fixed the issue with changing height on expanded vs closed.

**Review by krisstern — CHANGES_REQUESTED** [review]
The gap between the "Overall Trends" and "Monthly Analysis" buttons in the drawer seems to change for when the the "Monthly Analysis" is toggled. Please fix the gap size:

Screenshot 2024-06-24 at 2 14 26 AM
Screenshot 2024-06-24 at 2 14 37 AM

**Comment by shlomomdahan** [comment]
@krisstern Gap size fixed. 

Screenshot 2024-06-23 at 4 12 12 PM
Screenshot 2024-06-23 at 4 12 24 PM

**Review by krisstern — APPROVED** [review]

**Pull request merged**
