### PR TITLE
fix(updatecli): Typo

### PR DESCRIPTION
**Pull request by gounthar**
My [suggestion](https://github.com/jenkins-infra/stats.jenkins.io/pull/40#discussion_r1647294282) regarding this typo got ignored.

### CODE REVIEW

**Review by lemeurherve — CHANGES_REQUESTED** [review]
Cf https://github.com/jenkins-infra/stats.jenkins.io/pull/40#discussion_r1647317168

> I specifically set this to a lower case, to get a commit message from updatecli as I wanted:
> 
> > chore: bump `nodejs` version to 20.14.0 in .tool-versions
> 
> (See message of the existing commit created as a result of [jenkins-infra/contributor-spotlight#146](https://github.com/jenkins-infra/contributor-spotlight/pull/146): https://github.com/jenkins-infra/contributor-spotlight/pull/147/commits)

I'd like to keep this message that way, this wasn't a typo.

(Note: your suggestion wasn't ignored, the PR has been merged as soon as you approved the request as auto-merge was enabled)

**Comment by gounthar** [comment]
It's not consistent with the text of your message [earlier in the manifest](https://github.com/jenkins-infra/stats.jenkins.io/blob/main/updatecli/updatecli.d/nodejs.yaml#L2).
My suggestion was not addressed, as it was neither marked as resolved, nor responded to, nor committed. 🙂
This is not an issue in itself, merely an observation.
The suspected "typo" was not significant enough to request changes in your Pull Request; it was simply a minor nitpick, as this inconsistency caught my attention.

**Comment by lemeurherve** [comment]
This name concerns the manifest and isn't reused for PR title or commit message, while this target name is the commit message.
The fact that I've set them differently is intentional, not an inconsistency.

Your review consisted in a suggestion to set an upppercase to the "bump" in the target name (same in this PR), did I addressed it?

Removing my request for change, still -1 on this change.

**Comment by lemeurherve** [comment]
> My suggestion was not addressed, as it was neither marked as resolved, nor responded to, nor committed. 🙂

You're right I previously just answered it, now resolved.

**Review by krisstern — APPROVED** [review]

**Pull request merged**
